### ISSUE TITLE
Unable to see working dashboard and commands

### ISSUE THREAD

**Issue by black-eagle17** [Bekaboo/nvim#1]
Hello, I am trying to use this setup however I cannot get it to work. I see that some plugins are loaded but I cannot see the dashboard or anything else when I start nvim. Only floating window I can see is from the Lazy plugin. I am using the fish shell on arch linux.

**Comment by Bekaboo** [comment]
This is because the plugin for startup screen and relevant resources are removed since commit d49a2faa to make this configuration less bloated. If you like them you can revert this commit.

**Comment by black-eagle17** [comment]
Thank you for your work btw. Is there a way to enable all the default plugins at once?

**Comment by Bekaboo** [comment]
> Is there a way to enable all the default plugins at once?

By "enable" I assume you mean loading all of them into memory once nvim is started? This will slow down the startuptime, so plugins are lazy-loaded if possible. In theory the plugins will be always ready for use when needed given that the lazy-loading conditions are set properly. If you find a plugin not  loaded when you want to use it, you can report it here or change the lazy-loading condition in files under `lua/modules`.

**Comment by black-eagle17** [comment]
Thanks
