### ISSUE TITLE
Floating Statusline

### ISSUE THREAD

**Issue by ginesmoratalla** [Bekaboo/nvim#6]
Hey,

how do you make it so the status line is "floating" without touching the terminal's borders?

Thanks.
![Screenshot from 2024-09-01 14-51-24](https://github.com/user-attachments/assets/9403c713-e5e5-4af8-a352-f17a58ebe379)

**Comment by Bekaboo** [comment]
That's just terminal settings.

With alacritty:

```
[window.padding]
x = 8
y = 8
```
